import Head from "next/head";
import { Inter } from "@next/font/google";
import MainLayout from "@/components/Layouts/MainLayout";
import { ReactNode } from "react";
import WrapperContent from "@/components/Layouts/WrapperContent";
import FormLogin from "@/components/Shared/FormLogin";

const inter = Inter({ subsets: ["latin"] });

export default function Login() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        
            <WrapperContent>
                <FormLogin />
            </WrapperContent>

        </>
    );
}

Login.getLayout = (page: ReactNode) => {
    return (
        <MainLayout showHeader showFooter>
            {page}
        </MainLayout>
    );
};
