import Head from "next/head";
import { Inter } from "@next/font/google";
import MainLayout from "@/components/Layouts/MainLayout";
import { ReactNode } from "react";
import WrapperContent from "@/components/Layouts/WrapperContent";
import FormLogin from "@/components/Shared/FormLogin";
import { GetServerSideProps } from "next";
import { connectUser } from "@/services";
import { UserType } from "@/types";
import { getAccessTokenOnServer } from "@/utils/cookies";

export interface LoginProps {
    user: UserType
}

export default function Login({ user } : LoginProps) {

    console.log(user)

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        
            <WrapperContent>
                <FormLogin />
            </WrapperContent>

        </>
    );
}

export const getServerSideProps : GetServerSideProps = async (ctx) => {

    const token = getAccessTokenOnServer(ctx.req.headers.cookie as string)
    const userResponse = await connectUser(token as string);

    if(userResponse?.data.success) {
        return {
            redirect: {
                destination: "/",
                permanent: false
            }
        }
    }

    return {
        props: {}
    }
}

Login.getLayout = (page: ReactNode) => {
    return (
        <MainLayout showHeader showFooter>
            {page}
        </MainLayout>
    );
};
