export const REVALIDATE_TIME = 3 * 60 * 60;

export const GENRES_NT = [
    {id: "1", value: "Tất cả", slug: "truyen"},
    {id: "2", value: "Tiên Hiệp", slug: "genre=2"},
    {id: "3", value: "Huyền Huyễn", slug: "genre=3"},
    {id: "4", value: "Khoa Huyễn", slug: "genre=4"},
    {id: "5", value: "Võng Du", slug: "genre=5"},
    {id: "6", value: "Đô Thị", slug: "genre=6"},
    {id: "7", value: "Đồng Nhân", slug: "genre=7"},
    {id: "8", value: "Dã Sử", slug: "genre=8"},
    {id: "9", value: "Cạnh Kỹ", slug: "genre=9"},
    {id: "10", value: "Huyền Nghi", slug: "genre=10"},
    {id: "11", value: "Kiếm Hiệp", slug: "genre=11"},
    {id: "12", value: "Kỳ Ảo", slug: "genre=12"},
]

export const RANK_NT = [
    { id: "13", value: "Thịnh hành", slug: "thinh-hanh" },
    { id: "14", value: "Đọc nhiều", slug: "doc-nhieu" },
    { id: "15", value: "Tặng thưởng", slug: "tang-thuong" },
    { id: "16", value: "Đề cử", slug: "de-cu" },
    { id: "17", value: "Yêu thích", slug: "yeu-thich" },
    { id: "18", value: "Thảo luận", slug: "thao-luan" },
]

export const OPTIONS_CATEGORY_NT = [
    { value: "Tiên Hiệp", label: "Tiên Hiệp" },
    { value: "Huyền Huyễn", label: "Huyền Huyễn" },
    { value: "Khoa Huyễn", label: "Khoa Huyễn" },
    { value: "Võng Du", label: "Võng Du" },
    { value: "Đô Thị", label: "Đô Thị" },
    { value: "Đồng Nhân", label: "Đồng Nhân" },
    { value: "Dã Sử", label: "Dã Sử" },
    { value: "Cạnh Kỹ", label: "Cạnh Kỹ" },
    { value: "Huyền Nghi", label: "Huyền Nghi" },
    { value: "Kiếm Hiệp", label: "Kiếm Hiệp" },
    { value: "Kỳ Ảo", label: "Kỳ Ảo" },
]

export const OPTIONS_PERSONALITY = [
    { value: "Điềm Đạm", label: "Điềm Đạm" },
    { value: "Nhiệt Huyết", label: "Nhiệt Huyết" },
    { value: "Vô Sỉ", label: "Vô Sỉ" },
    { value: "Thiết Huyết", label: "Thiết Huyết" },
    { value: "Nhẹ Nhàng", label: "Nhẹ Nhàng" },
    { value: "Cơ Trí", label: "Cơ Trí" },
    { value: "Lãnh Khốc", label: "Lãnh Khốc" },
    { value: "Kiêu Ngạo", label: "Kiêu Ngạo" },
    { value: "Ngu Ngốc", label: "Ngu Ngốc" },
    { value: "Giảo Hoạt", label: "Giảo Hoạt" },
]

export const OPTIONS_SCENE_NT = [
    { value: "", label: "" },
    { value: "", label: "" },
    { value: "", label: "" },
    { value: "", label: "" },
    { value: "", label: "" },
    { value: "", label: "" },
    { value: "", label: "" },
    { value: "", label: "" },
    { value: "", label: "" },
    { value: "", label: "" },
    { value: "", label: "" },
    { value: "", label: "" },
    { value: "", label: "" },
    { value: "", label: "" },
    { value: "", label: "" },
    { value: "", label: "" },
    { value: "", label: "" },
    { value: "", label: "" },
    { value: "", label: "" },
    { value: "", label: "" },
    { value: "", label: "" },
    { value: "", label: "" },
    { value: "", label: "" },
    { value: "", label: "" },
    { value: "", label: "" },
    { value: "", label: "" },
    { value: "", label: "" },
    { value: "", label: "" },
    { value: "", label: "" },
    { value: "", label: "" },
    { value: "", label: "" },
    { value: "", label: "" },
    { value: "", label: "" },
    { value: "", label: "" },
    { value: "", label: "" },
    { value: "", label: "" },
    { value: "", label: "" },
    { value: "", label: "" },
    { value: "", label: "" },
    { value: "", label: "" },
    { value: "", label: "" },
    { value: "", label: "" },
    { value: "", label: "" },
    { value: "", label: "" },
    { value: "", label: "" },
    { value: "", label: "" },
]