import Head from "next/head";
import { GetServerSideProps, NextPage } from "next";

import WrapperContent from "@/components/Layouts/WrapperContent";
import FormHome from "@/components/Shared/FormHome";
import axios from "axios";

const Home : NextPage = ({ name } : any) => {

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        
            <WrapperContent>
                <FormHome />
            </WrapperContent>

        </>
    );
}

export const getServerSideProps : GetServerSideProps = async (ctx) => {

    const response = await axios.get("http://localhost:4000/api/users");

    return {
        props: {
            name: response.data || null
        }
    }
}


export default Home;
